<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Export</name>
   <tag></tag>
   <elementGuidId>a5e66042-7170-4c47-bad9-e5bb151abb9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href='https://ydtwebstaging.com/1b655f54-a30c-429c-8279-8c1430be44b2'][count(. | //a[@download = 'case_log.csv' and @class = 'but' and @target = '_blank' and @href = 'blob:https://ydtwebstaging.com/cca77b95-7ff7-49d4-a842-8efc69e0b329' and (text() = 'Export' or . = 'Export')]) = count(//a[@download = 'case_log.csv' and @class = 'but' and @target = '_blank' and @href = 'blob:https://ydtwebstaging.com/cca77b95-7ff7-49d4-a842-8efc69e0b329' and (text() = 'Export' or . = 'Export')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Logs']/div[4]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>download</name>
      <type>Main</type>
      <value>case_log.csv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>but</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>blob:https://ydtwebstaging.com/cca77b95-7ff7-49d4-a842-8efc69e0b329</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href='https://ydtwebstaging.com/1b655f54-a30c-429c-8279-8c1430be44b2']</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//a[contains(text(),'Export')]</value>
   </webElementXpaths>
</WebElementEntity>
